Add test for "mov" and "(mov|add|adds|sub|subs)_imm"
fujitsu/xbyak_aarch64 pull request #67
Opened 2022-11-03 17:54 UTC by bkmgit

Additional tests for arithmetic and mov to be used in CI.
Addressing https://github.com/fujitsu/xbyak_aarch64/issues/27
Unclear if the codes should be refactored.

2022-11-04 08:03 UTC, kawakami-k commented
Thank you for the PR, but the tesfs of `*_imm` have already been implemented as [mov_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/mov_imm.cpp) and [add_sub_adds_subs_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/add_sub_adds_subs_imm.cpp).

These files should be compiled and executed in `test_all.sh`.

2022-11-04 08:52 UTC, bkmgit commented
`test_all.sh` calls `test_integrated.sh` which compiles and executes  [mov.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/mov_imm.cpp), [mov_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/mov_imm.cpp) and [add_sub_adds_subs_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/add_sub_adds_subs_imm.cpp). Should the contents of `test_integrated.sh` be put in `test_nm.sh` which is what calls the other tests? A few changes are needed to run these tests compared to the other tests in `test_nm.sh`.

2022-11-04 13:03 UTC, kawakami-k requested changes
Thank you for the PR!
 Could you please chane three miner points?
- Two lines for `Copyright 201-2022 FUJITSU LIMITED`.
- `${EMULATOR} ./${TEST_FILE} > ${TEST_FILE}.log 2>&1`

2022-11-04 13:03 UTC, kawakami-k commented on test/test_integrated.sh
> +./${TEST_FILE} > a.asm
Could you please change this line?
```
${EMULATOR} ./${TEST_FILE} > ${TEST_FILE}.log 2>&1
```

2022-11-04 13:03 UTC, kawakami-k commented on test/test_integrated.sh
> +# Copyright 2019-2021 FUJITSU LIMITED
Could you please change this line?
```
# Copyright 2019-2022 FUJITSU LIMITED
```

2022-11-04 14:39 UTC, bkmgit commented on test/test_integrated.sh
> +# Copyright 2019-2021 FUJITSU LIMITED
Done.

2022-11-04 14:39 UTC, bkmgit commented on test/test_integrated.sh
> +./${TEST_FILE} > a.asm
Done.

2022-11-04 23:35 UTC, kawakami-k commented
> `test_all.sh` calls `test_integrated.sh` which compiles and executes [mov.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/mov_imm.cpp), [mov_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/mov_imm.cpp) and [add_sub_adds_subs_imm.cpp](https://github.com/fujitsu/xbyak_aarch64/blob/9832b380e7a85a41635a9de84d50bbf54f44e9b6/test/add_sub_adds_subs_imm.cpp). Should the contents of `test_integrated.sh` be put in `test_nm.sh` which is what calls the other tests? A few changes are needed to run these tests compared to the other tests in `test_nm.sh`.

Sorry, I made a mistake. You're right.
Thank you for the contribution.

2022-11-04 23:35 UTC, merged

2022-11-05 08:58 UTC, bkmgit commented
Welcome. Thanks for the code.